<?php

namespace Database\Seeders;

use App\Models\Alumni;
use Illuminate\Database\Seeder;

class AlumniSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'nama' => 'Laila Putri',
                'nim' => '190102001',
                'prodi' => 'Informatika',
                'fakultas' => 'Teknik',
                'tahun_masuk' => 2019,
                'tahun_lulus' => 2023,
                'email' => '190102001@alumni.test',
                'nik' => '320101230001',
                'no_hp' => '081234567001',
                'alamat' => 'Jl. Merpati No. 12, Bandung',
                'tanggal_lahir' => '1999-03-12',
                'status_pekerjaan' => 'Bekerja',
            ],
            [
                'nama' => 'Rizky Pratama',
                'nim' => '190102014',
                'prodi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'tahun_masuk' => 2018,
                'tahun_lulus' => 2022,
                'email' => '190102014@alumni.test',
                'nik' => '320101230014',
                'no_hp' => '081234567014',
                'alamat' => 'Jl. Kenari No. 8, Jakarta',
                'tanggal_lahir' => '1998-11-05',
                'status_pekerjaan' => 'Wiraswasta',
            ],
            [
                'nama' => 'Nanda Saputra',
                'nim' => '190301022',
                'prodi' => 'Manajemen',
                'fakultas' => 'Ekonomi',
                'tahun_masuk' => 2017,
                'tahun_lulus' => 2021,
                'email' => '190301022@alumni.test',
                'nik' => '320101230022',
                'no_hp' => '081234567022',
                'alamat' => 'Jl. Mawar No. 21, Surabaya',
                'tanggal_lahir' => '1997-07-21',
                'status_pekerjaan' => 'Mencari kerja',
            ],
            [
                'nama' => 'Aulia Rahman',
                'nim' => '190204011',
                'prodi' => 'Hukum',
                'fakultas' => 'Hukum',
                'tahun_masuk' => 2016,
                'tahun_lulus' => 2020,
                'email' => '190204011@alumni.test',
                'nik' => '320101230011',
                'no_hp' => '081234567011',
                'alamat' => 'Jl. Kamboja No. 5, Yogyakarta',
                'tanggal_lahir' => '1996-02-17',
                'status_pekerjaan' => 'Bekerja',
            ],
            [
                'nama' => 'Dewi Kusuma',
                'nim' => '190501008',
                'prodi' => 'Psikologi',
                'fakultas' => 'Psikologi',
                'tahun_masuk' => 2019,
                'tahun_lulus' => 2023,
                'email' => '190501008@alumni.test',
                'nik' => '320101230008',
                'no_hp' => '081234567008',
                'alamat' => 'Jl. Anggrek No. 17, Semarang',
                'tanggal_lahir' => '1999-09-09',
                'status_pekerjaan' => 'Melanjutkan studi',
            ],
            [
                'nama' => 'Samuel Hutabarat',
                'nim' => '190402031',
                'prodi' => 'Akuntansi',
                'fakultas' => 'Ekonomi',
                'tahun_masuk' => 2018,
                'tahun_lulus' => 2022,
                'email' => '190402031@alumni.test',
                'nik' => '320101230031',
                'no_hp' => '081234567031',
                'alamat' => 'Jl. Diponegoro No. 45, Medan',
                'tanggal_lahir' => '1998-01-30',
                'status_pekerjaan' => 'Bekerja',
            ],
            [
                'nama' => 'Mega Lestari',
                'nim' => '190103019',
                'prodi' => 'Teknik Sipil',
                'fakultas' => 'Teknik',
                'tahun_masuk' => 2016,
                'tahun_lulus' => 2020,
                'email' => '190103019@alumni.test',
                'nik' => '320101230019',
                'no_hp' => '081234567019',
                'alamat' => 'Jl. Gatot Subroto No. 88, Bandung',
                'tanggal_lahir' => '1996-12-11',
                'status_pekerjaan' => 'Bekerja',
            ],
            [
                'nama' => 'Bagas Mahendra',
                'nim' => '190602041',
                'prodi' => 'Ilmu Komunikasi',
                'fakultas' => 'Ilmu Sosial',
                'tahun_masuk' => 2017,
                'tahun_lulus' => 2021,
                'email' => '190602041@alumni.test',
                'nik' => '320101230041',
                'no_hp' => '081234567041',
                'alamat' => 'Jl. Cendana No. 3, Depok',
                'tanggal_lahir' => '1997-05-25',
                'status_pekerjaan' => 'Mencari kerja',
            ],
            [
                'nama' => 'Salsa Nirmala',
                'nim' => '190701055',
                'prodi' => 'Keperawatan',
                'fakultas' => 'Kesehatan',
                'tahun_masuk' => 2018,
                'tahun_lulus' => 2022,
                'email' => '190701055@alumni.test',
                'nik' => '320101230055',
                'no_hp' => '081234567055',
                'alamat' => 'Jl. Melati No. 6, Malang',
                'tanggal_lahir' => '1998-08-14',
                'status_pekerjaan' => 'Bekerja',
            ],
            [
                'nama' => 'Dani Firmansyah',
                'nim' => '190802009',
                'prodi' => 'Pendidikan Matematika',
                'fakultas' => 'Keguruan',
                'tahun_masuk' => 2019,
                'tahun_lulus' => 2023,
                'email' => '190802009@alumni.test',
                'nik' => '320101230009',
                'no_hp' => '081234567009',
                'alamat' => 'Jl. Teratai No. 9, Bandung',
                'tanggal_lahir' => '1999-04-02',
                'status_pekerjaan' => 'Belum bekerja',
            ],
        ];

        foreach ($rows as $row) {
            Alumni::updateOrCreate(['nim' => $row['nim']], $row);
        }
    }
}
